"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    const branches = [
      {
        id: "550e8400-e29b-41d4-a716-446655440001",
        name: "Headquarters",
        code: "HQ",
        description: "Main company headquarters",
        address: JSON.stringify({
          street: "123 Main Street",
          city: "New York",
          state: "NY",
          country: "USA",
          postalCode: "10001",
        }),
        contactInfo: JSON.stringify({
          email: "hq@company.com",
          phone: "+1-555-0101",
          fax: "+1-555-0102",
        }),
        managerId: null, // Will be set after employees are created
        parentBranchId: null,
        timezone: "America/New_York",
        workingHours: JSON.stringify({
          monday: { start: "09:00", end: "17:00", isWorking: true },
          tuesday: { start: "09:00", end: "17:00", isWorking: true },
          wednesday: { start: "09:00", end: "17:00", isWorking: true },
          thursday: { start: "09:00", end: "17:00", isWorking: true },
          friday: { start: "09:00", end: "17:00", isWorking: true },
          saturday: { start: "09:00", end: "13:00", isWorking: false },
          sunday: { start: "00:00", end: "00:00", isWorking: false },
        }),
        capacity: 500,
        currentEmployees: 0,
        facilities: JSON.stringify([
          "Conference Rooms",
          "Cafeteria",
          "Gym",
          "Parking",
        ]),
        status: "active",
        isHeadquarters: true,
        establishedDate: "2020-01-01",
        notes: "Main corporate office",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440002",
        name: "West Coast Office",
        code: "WC",
        description: "West Coast regional office",
        address: JSON.stringify({
          street: "456 Tech Avenue",
          city: "San Francisco",
          state: "CA",
          country: "USA",
          postalCode: "94105",
        }),
        contactInfo: JSON.stringify({
          email: "westcoast@company.com",
          phone: "+1-555-0201",
          fax: "+1-555-0202",
        }),
        managerId: null,
        parentBranchId: "550e8400-e29b-41d4-a716-446655440001",
        timezone: "America/Los_Angeles",
        workingHours: JSON.stringify({
          monday: { start: "08:00", end: "17:00", isWorking: true },
          tuesday: { start: "08:00", end: "17:00", isWorking: true },
          wednesday: { start: "08:00", end: "17:00", isWorking: true },
          thursday: { start: "08:00", end: "17:00", isWorking: true },
          friday: { start: "08:00", end: "16:00", isWorking: true },
          saturday: { start: "09:00", end: "13:00", isWorking: false },
          sunday: { start: "00:00", end: "00:00", isWorking: false },
        }),
        capacity: 200,
        currentEmployees: 0,
        facilities: JSON.stringify([
          "Open Workspace",
          "Kitchen",
          "Meeting Rooms",
        ]),
        status: "active",
        isHeadquarters: false,
        establishedDate: "2021-03-15",
        notes: "Technology-focused office",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440003",
        name: "European Office",
        code: "EU",
        description: "European regional headquarters",
        address: JSON.stringify({
          street: "789 Business Street",
          city: "London",
          state: "",
          country: "UK",
          postalCode: "SW1A 1AA",
        }),
        contactInfo: JSON.stringify({
          email: "europe@company.com",
          phone: "+44-20-7946-0958",
          fax: "+44-20-7946-0959",
        }),
        managerId: null,
        parentBranchId: "550e8400-e29b-41d4-a716-446655440001",
        timezone: "Europe/London",
        workingHours: JSON.stringify({
          monday: { start: "09:00", end: "18:00", isWorking: true },
          tuesday: { start: "09:00", end: "18:00", isWorking: true },
          wednesday: { start: "09:00", end: "18:00", isWorking: true },
          thursday: { start: "09:00", end: "18:00", isWorking: true },
          friday: { start: "09:00", end: "17:00", isWorking: true },
          saturday: { start: "09:00", end: "13:00", isWorking: false },
          sunday: { start: "00:00", end: "00:00", isWorking: false },
        }),
        capacity: 150,
        currentEmployees: 0,
        facilities: JSON.stringify([
          "Private Offices",
          "Boardroom",
          "Break Room",
        ]),
        status: "active",
        isHeadquarters: false,
        establishedDate: "2021-06-01",
        notes: "European operations center",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "550e8400-e29b-41d4-a716-446655440004",
        name: "Asia Pacific Office",
        code: "AP",
        description: "Asia Pacific regional office",
        address: JSON.stringify({
          street: "321 Innovation Road",
          city: "Singapore",
          state: "",
          country: "Singapore",
          postalCode: "018956",
        }),
        contactInfo: JSON.stringify({
          email: "apac@company.com",
          phone: "+65-6123-4567",
          fax: "+65-6123-4568",
        }),
        managerId: null,
        parentBranchId: "550e8400-e29b-41d4-a716-446655440001",
        timezone: "Asia/Singapore",
        workingHours: JSON.stringify({
          monday: { start: "08:30", end: "18:30", isWorking: true },
          tuesday: { start: "08:30", end: "18:30", isWorking: true },
          wednesday: { start: "08:30", end: "18:30", isWorking: true },
          thursday: { start: "08:30", end: "18:30", isWorking: true },
          friday: { start: "08:30", end: "17:30", isWorking: true },
          saturday: { start: "09:00", end: "13:00", isWorking: false },
          sunday: { start: "00:00", end: "00:00", isWorking: false },
        }),
        capacity: 100,
        currentEmployees: 0,
        facilities: JSON.stringify([
          "Collaborative Space",
          "Quiet Rooms",
          "Café",
        ]),
        status: "active",
        isHeadquarters: false,
        establishedDate: "2022-01-10",
        notes: "APAC operations hub",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    await queryInterface.bulkInsert("branches", branches, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("branches", null, {});
  },
};
